/**
 * Données de démonstration — SENSIA Manager
 * Données fictives mais cohérentes pour présenter l'application.
 */

import type {
  DashboardData, Client, ClientDetail, Project, Invoice,
  Activity, Task, DiagnosticItem,
} from './api'

// ─── CLIENTS ─────────────────────────────────────────────────

export const DEMO_CLIENTS: Client[] = [
  {
    id: 1,
    name: 'TechVision SAS',
    slug: 'techvision-sas',
    type: 'entreprise',
    sector: 'Technologie & SaaS',
    status: 'active',
    pipeline_stage: 'negociation',
    contact_name: 'Isabelle Fontaine',
    contact_email: 'i.fontaine@techvision.fr',
    contact_phone: '06 12 34 56 78',
    website: 'https://techvision.fr',
    budget_range: '50k-100k',
    projects_count: 2,
    created_at: '2025-09-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'Cabinet Dupont & Associés',
    slug: 'cabinet-dupont',
    type: 'entreprise',
    sector: 'Services financiers',
    status: 'active',
    pipeline_stage: 'client',
    contact_name: 'Marc Dupont',
    contact_email: 'm.dupont@cabinet-dupont.fr',
    contact_phone: '01 44 55 66 77',
    budget_range: '20k-50k',
    projects_count: 2,
    created_at: '2025-07-03T09:30:00Z',
  },
  {
    id: 3,
    name: 'MedConnect',
    slug: 'medconnect',
    type: 'startup',
    sector: 'Santé numérique',
    status: 'active',
    pipeline_stage: 'client',
    contact_name: 'Sophie Leroux',
    contact_email: 's.leroux@medconnect.io',
    contact_phone: '07 89 01 23 45',
    website: 'https://medconnect.io',
    budget_range: '50k-100k',
    projects_count: 1,
    created_at: '2025-10-20T14:00:00Z',
  },
  {
    id: 4,
    name: 'Boulangerie Artisans du Pain',
    slug: 'artisans-du-pain',
    type: 'tpe',
    sector: 'Alimentation & Retail',
    status: 'active',
    pipeline_stage: 'client',
    contact_name: 'Jean-Claude Martin',
    contact_email: 'jc.martin@artisansdupain.fr',
    contact_phone: '06 55 44 33 22',
    budget_range: '5k-20k',
    projects_count: 1,
    created_at: '2025-11-08T08:00:00Z',
  },
  {
    id: 5,
    name: 'EcoLogis Habitat',
    slug: 'ecologis-habitat',
    type: 'pme',
    sector: 'BTP & Immobilier',
    status: 'prospect',
    pipeline_stage: 'qualification',
    contact_name: 'Nathalie Bergeron',
    contact_email: 'n.bergeron@ecologis.fr',
    contact_phone: '06 78 90 12 34',
    budget_range: '20k-50k',
    projects_count: 0,
    created_at: '2026-01-10T11:00:00Z',
  },
  {
    id: 6,
    name: 'StartupXcel',
    slug: 'startupxcel',
    type: 'startup',
    sector: 'Technologie',
    status: 'prospect',
    pipeline_stage: 'decouverte',
    contact_name: 'Antoine Moreau',
    contact_email: 'a.moreau@startupxcel.io',
    contact_phone: '07 11 22 33 44',
    budget_range: '10k-20k',
    projects_count: 0,
    created_at: '2026-02-05T15:30:00Z',
  },
  {
    id: 7,
    name: 'RetailPro Distribution',
    slug: 'retailpro',
    type: 'pme',
    sector: 'Commerce & Distribution',
    status: 'inactive',
    pipeline_stage: 'perdu',
    contact_name: 'Camille Petit',
    contact_email: 'c.petit@retailpro.fr',
    contact_phone: '01 22 33 44 55',
    budget_range: '20k-50k',
    projects_count: 1,
    created_at: '2025-05-12T10:00:00Z',
  },
]

// ─── PROJETS ─────────────────────────────────────────────────

export const DEMO_PROJECTS: Project[] = [
  {
    id: 1,
    code: 'PRJ-2025-001',
    name: 'Transformation IA — TechVision',
    client_id: 1,
    client_name: 'TechVision SAS',
    type: 'ia',
    status: 'en_cours',
    phase: 4,
    description: "Intégration d'un moteur IA générative dans la plateforme SaaS TechVision.",
    budget: 85000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2025-10-01',
    end_date: '2026-04-30',
    created_at: '2025-09-20T10:00:00Z',
  },
  {
    id: 2,
    code: 'PRJ-2025-002',
    name: 'Audit Cybersécurité — Cabinet Dupont',
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    type: 'cyber',
    status: 'termine',
    phase: 8,
    description: 'Audit complet de sécurité SI et conformité RGPD.',
    budget: 22000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2025-07-10',
    end_date: '2025-10-15',
    created_at: '2025-07-05T09:00:00Z',
  },
  {
    id: 3,
    code: 'PRJ-2025-003',
    name: 'Plateforme RGPD — MedConnect',
    client_id: 3,
    client_name: 'MedConnect',
    type: 'rgpd',
    status: 'en_cours',
    phase: 3,
    description: 'Mise en conformité RGPD et gestion des consentements patients.',
    budget: 48000,
    contract_signed: true,
    gdpr_done: false,
    start_date: '2025-11-01',
    end_date: '2026-05-31',
    created_at: '2025-10-25T14:00:00Z',
  },
  {
    id: 4,
    code: 'PRJ-2025-004',
    name: 'Chatbot IA Commandes — Artisans du Pain',
    client_id: 4,
    client_name: 'Boulangerie Artisans du Pain',
    type: 'ia',
    status: 'en_cours',
    phase: 6,
    description: "Assistant IA pour la gestion des commandes en ligne et fidélisation client.",
    budget: 12000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2025-12-01',
    end_date: '2026-03-31',
    created_at: '2025-11-10T08:00:00Z',
  },
  {
    id: 5,
    code: 'PRJ-2025-005',
    name: 'Stratégie Data — Cabinet Dupont',
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    type: 'data',
    status: 'en_cours',
    phase: 2,
    description: "Construction d'un entrepôt de données et tableaux de bord analytiques.",
    budget: 35000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2026-01-15',
    end_date: '2026-07-31',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 6,
    code: 'PRJ-2025-006',
    name: 'Automatisation RH — TechVision',
    client_id: 1,
    client_name: 'TechVision SAS',
    type: 'automatisation',
    status: 'en_cours',
    phase: 5,
    description: 'Automatisation des processus RH : onboarding, paie, congés.',
    budget: 28000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2025-11-15',
    end_date: '2026-04-15',
    created_at: '2025-11-01T10:00:00Z',
  },
  {
    id: 7,
    code: 'PRJ-2024-007',
    name: 'Refonte SI — RetailPro',
    client_id: 7,
    client_name: 'RetailPro Distribution',
    type: 'conseil',
    status: 'suspendu',
    phase: 5,
    description: "Refonte du système d'information et migration cloud.",
    budget: 65000,
    contract_signed: true,
    gdpr_done: true,
    start_date: '2025-03-01',
    end_date: '2025-12-31',
    created_at: '2025-02-20T10:00:00Z',
  },
]

// ─── CLIENT DETAILS ──────────────────────────────────────────

export const DEMO_CLIENT_DETAILS: Record<number, ClientDetail> = {
  1: {
    ...DEMO_CLIENTS[0],
    address: '12 rue de la République, 75011 Paris',
    siret: '84312567800023',
    source: 'Recommandation',
    notes: 'Client stratégique. Très intéressé par nos offres IA générative pour leur équipe R&D.',
    projects: DEMO_PROJECTS.filter(p => p.client_id === 1),
    contacts: [
      { id: 1, name: 'Isabelle Fontaine', email: 'i.fontaine@techvision.fr', phone: '06 12 34 56 78', role: 'DGA', is_primary: true },
      { id: 2, name: 'Thomas Renard', email: 't.renard@techvision.fr', phone: '06 99 88 77 66', role: 'CTO', is_primary: false },
    ],
  },
  2: {
    ...DEMO_CLIENTS[1],
    address: '8 avenue Haussmann, 75008 Paris',
    siret: '31245678900012',
    source: 'LinkedIn',
    notes: 'Cabinet comptable avec 45 collaborateurs. Fort besoin de digitalisation.',
    projects: DEMO_PROJECTS.filter(p => p.client_id === 2),
    contacts: [
      { id: 3, name: 'Marc Dupont', email: 'm.dupont@cabinet-dupont.fr', phone: '01 44 55 66 77', role: 'Associé gérant', is_primary: true },
      { id: 4, name: 'Élise Moreau', email: 'e.moreau@cabinet-dupont.fr', phone: '01 44 55 66 78', role: 'DSI', is_primary: false },
    ],
  },
  3: {
    ...DEMO_CLIENTS[2],
    address: '42 rue de Bercy, 75012 Paris',
    siret: '90123456700034',
    source: 'Événement',
    notes: 'Startup en forte croissance. Enjeux RGPD critiques liés aux données de santé.',
    projects: DEMO_PROJECTS.filter(p => p.client_id === 3),
    contacts: [
      { id: 5, name: 'Sophie Leroux', email: 's.leroux@medconnect.io', phone: '07 89 01 23 45', role: 'CEO', is_primary: true },
    ],
  },
  4: {
    ...DEMO_CLIENTS[3],
    address: '3 place du Marché, 69001 Lyon',
    siret: '41234567800056',
    source: 'Bouche à oreille',
    notes: '3 boulangeries. Veut automatiser les commandes et améliorer la fidélisation.',
    projects: DEMO_PROJECTS.filter(p => p.client_id === 4),
    contacts: [
      { id: 6, name: 'Jean-Claude Martin', email: 'jc.martin@artisansdupain.fr', phone: '06 55 44 33 22', role: 'Gérant', is_primary: true },
    ],
  },
  5: {
    ...DEMO_CLIENTS[4],
    address: '15 rue de la Paix, 33000 Bordeaux',
    siret: '78901234500067',
    source: 'LinkedIn',
    notes: 'Promoteur immobilier intéressé par la digitalisation de ses processus.',
    projects: [],
    contacts: [
      { id: 7, name: 'Nathalie Bergeron', email: 'n.bergeron@ecologis.fr', phone: '06 78 90 12 34', role: 'DG', is_primary: true },
    ],
  },
  6: {
    ...DEMO_CLIENTS[5],
    address: '7 rue de la Tech, 75020 Paris',
    siret: '89012345600078',
    source: 'Recommandation',
    notes: 'Startup B2B SaaS cherchant à intégrer IA dans leur produit.',
    projects: [],
    contacts: [
      { id: 8, name: 'Antoine Moreau', email: 'a.moreau@startupxcel.io', phone: '07 11 22 33 44', role: 'CTO', is_primary: true },
    ],
  },
  7: {
    ...DEMO_CLIENTS[6],
    address: '22 boulevard des Capucines, 75009 Paris',
    siret: '32109876500089',
    source: 'Appel entrant',
    notes: 'Projet suspendu suite à changement de direction. Suivi à reprendre Q2 2026.',
    projects: DEMO_PROJECTS.filter(p => p.client_id === 7),
    contacts: [
      { id: 9, name: 'Camille Petit', email: 'c.petit@retailpro.fr', phone: '01 22 33 44 55', role: 'DAF', is_primary: true },
    ],
  },
}

// ─── FACTURES ────────────────────────────────────────────────

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 1,
    number: 'FAC-2025-001',
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    project_id: 2,
    amount_ht: 11000,
    amount_ttc: 13200,
    tva_rate: 20,
    status: 'payee',
    issued_date: '2025-07-15',
    due_date: '2025-08-15',
    paid_date: '2025-08-10',
    notes: 'Acompte 50% — Audit Cybersécurité',
    created_at: '2025-07-15T10:00:00Z',
  },
  {
    id: 2,
    number: 'FAC-2025-002',
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    project_id: 2,
    amount_ht: 11000,
    amount_ttc: 13200,
    tva_rate: 20,
    status: 'payee',
    issued_date: '2025-10-20',
    due_date: '2025-11-20',
    paid_date: '2025-11-18',
    notes: 'Solde — Audit Cybersécurité',
    created_at: '2025-10-20T10:00:00Z',
  },
  {
    id: 3,
    number: 'FAC-2025-003',
    client_id: 1,
    client_name: 'TechVision SAS',
    project_id: 1,
    amount_ht: 25000,
    amount_ttc: 30000,
    tva_rate: 20,
    status: 'payee',
    issued_date: '2025-10-05',
    due_date: '2025-11-05',
    paid_date: '2025-11-02',
    notes: 'Acompte 30% — Transformation IA',
    created_at: '2025-10-05T10:00:00Z',
  },
  {
    id: 4,
    number: 'FAC-2025-004',
    client_id: 4,
    client_name: 'Boulangerie Artisans du Pain',
    project_id: 4,
    amount_ht: 6000,
    amount_ttc: 7200,
    tva_rate: 20,
    status: 'payee',
    issued_date: '2025-12-05',
    due_date: '2026-01-05',
    paid_date: '2025-12-28',
    notes: 'Acompte 50% — Chatbot IA',
    created_at: '2025-12-05T10:00:00Z',
  },
  {
    id: 5,
    number: 'FAC-2026-001',
    client_id: 3,
    client_name: 'MedConnect',
    project_id: 3,
    amount_ht: 16000,
    amount_ttc: 19200,
    tva_rate: 20,
    status: 'envoyee',
    issued_date: '2026-01-10',
    due_date: '2026-02-10',
    notes: 'Acompte 33% — RGPD MedConnect',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 6,
    number: 'FAC-2026-002',
    client_id: 1,
    client_name: 'TechVision SAS',
    project_id: 6,
    amount_ht: 14000,
    amount_ttc: 16800,
    tva_rate: 20,
    status: 'envoyee',
    issued_date: '2026-02-01',
    due_date: '2026-03-01',
    notes: 'Jalons 1-2 — Automatisation RH',
    created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 7,
    number: 'FAC-2026-003',
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    project_id: 5,
    amount_ht: 10000,
    amount_ttc: 12000,
    tva_rate: 20,
    status: 'brouillon',
    issued_date: '2026-03-01',
    due_date: '2026-04-01',
    notes: 'Acompte — Stratégie Data',
    created_at: '2026-03-01T10:00:00Z',
  },
]

// ─── CRM — ACTIVITÉS ─────────────────────────────────────────

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 1,
    title: 'Appel de suivi projet IA',
    description: 'Point mensuel avec Isabelle — avancement phase 4, validation maquettes.',
    client_id: 1,
    project_id: 1,
    type: 'appel',
    date: '2026-03-15T10:30:00Z',
    duration_minutes: 45,
    created_at: '2026-03-15T10:30:00Z',
  },
  {
    id: 2,
    title: 'Réunion démarrage Stratégie Data',
    description: 'Kick-off avec Marc Dupont et son équipe DSI. Définition des sources de données.',
    client_id: 2,
    project_id: 5,
    type: 'reunion',
    date: '2026-01-16T14:00:00Z',
    duration_minutes: 120,
    created_at: '2026-01-16T14:00:00Z',
  },
  {
    id: 3,
    title: 'Envoi rapport audit cybersécurité',
    description: 'Livraison du rapport final avec 23 recommandations priorisées.',
    client_id: 2,
    project_id: 2,
    type: 'email',
    date: '2025-10-18T09:00:00Z',
    duration_minutes: 30,
    created_at: '2025-10-18T09:00:00Z',
  },
  {
    id: 4,
    title: 'Demo chatbot IA v1',
    description: 'Présentation de la version beta du chatbot à Jean-Claude Martin.',
    client_id: 4,
    project_id: 4,
    type: 'demo',
    date: '2026-02-20T11:00:00Z',
    duration_minutes: 60,
    created_at: '2026-02-20T11:00:00Z',
  },
  {
    id: 5,
    title: 'Premier contact EcoLogis',
    description: 'Appel découverte avec Nathalie Bergeron — besoins en transformation digitale.',
    client_id: 5,
    type: 'appel',
    date: '2026-01-12T16:00:00Z',
    duration_minutes: 30,
    created_at: '2026-01-12T16:00:00Z',
  },
  {
    id: 6,
    title: 'Envoi proposition commerciale EcoLogis',
    description: 'Proposition SENSIA pour accompagnement IA — 3 scénarios budget.',
    client_id: 5,
    type: 'email',
    date: '2026-01-20T10:00:00Z',
    duration_minutes: 15,
    created_at: '2026-01-20T10:00:00Z',
  },
]

// ─── CRM — TÂCHES ────────────────────────────────────────────

export const DEMO_TASKS: Task[] = [
  {
    id: 1,
    title: 'Préparer démo phase 5 TechVision',
    description: 'Préparer la démonstration du module automatisation pour la semaine prochaine.',
    client_id: 1,
    project_id: 1,
    type: 'livrable',
    priority: 'haute',
    status: 'en_cours',
    due_date: '2026-03-25',
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 2,
    title: 'Relancer MedConnect — validation RGPD',
    description: 'Suivre la validation du registre des traitements avec Sophie Leroux.',
    client_id: 3,
    project_id: 3,
    type: 'relance',
    priority: 'haute',
    status: 'a_faire',
    due_date: '2026-03-20',
    created_at: '2026-03-12T09:00:00Z',
  },
  {
    id: 3,
    title: 'Envoyer devis EcoLogis',
    description: "Finaliser et envoyer le devis pour la mission de conseil stratégie IA.",
    client_id: 5,
    type: 'commercial',
    priority: 'moyenne',
    status: 'a_faire',
    due_date: '2026-03-28',
    created_at: '2026-03-15T14:00:00Z',
  },
  {
    id: 4,
    title: 'Livrer rapport mensuel Cabinet Dupont',
    description: "Rapport d'avancement Stratégie Data — Mars 2026.",
    client_id: 2,
    project_id: 5,
    type: 'livrable',
    priority: 'normale',
    status: 'a_faire',
    due_date: '2026-03-31',
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 5,
    title: 'Mise en production chatbot boulangerie',
    description: 'Déploiement v1.0 en production + formation Jean-Claude.',
    client_id: 4,
    project_id: 4,
    type: 'livrable',
    priority: 'haute',
    status: 'a_faire',
    due_date: '2026-03-22',
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 6,
    title: 'Facture solde TechVision PRJ-001',
    description: 'Émettre la facture de solde après validation client.',
    client_id: 1,
    project_id: 1,
    type: 'administratif',
    priority: 'normale',
    status: 'a_faire',
    due_date: '2026-04-30',
    created_at: '2026-03-01T10:00:00Z',
  },
]

// ─── DIAGNOSTICS ─────────────────────────────────────────────

export const DEMO_DIAGNOSTICS: DiagnosticItem[] = [
  {
    id: 1,
    client_id: 2,
    client_name: 'Cabinet Dupont & Associés',
    type: 'cyber',
    title: 'Audit Cybersécurité — Cabinet Dupont 2025',
    status: 'termine',
    share_token: 'demo-token-cyber-001',
    company_info: {
      company_name: 'Cabinet Dupont & Associés',
      sector: 'Services financiers',
      employees: '40-50',
      contact_name: 'Marc Dupont',
    },
    answers: {},
    results: {
      global_score: 62,
      sections: [
        { id: 'gouvernance', title: 'Gouvernance & Organisation', score_pct: 75, preconisations: ['Formaliser une politique de sécurité SI', 'Désigner un RSSI ou référent cybersécurité'] },
        { id: 'protection', title: 'Protection des données', score_pct: 58, preconisations: ['Chiffrer les disques des postes nomades', 'Mettre en place un DLP (Data Loss Prevention)'] },
        { id: 'detection', title: 'Détection & Réponse', score_pct: 45, preconisations: ["Déployer un SIEM pour la corrélation d'événements", 'Définir un plan de réponse aux incidents'] },
        { id: 'resilience', title: 'Résilience & Continuité', score_pct: 70, preconisations: ['Tester le PRA annuellement', 'Sauvegardes hors-site à valider'] },
      ],
    },
    created_at: '2025-07-12T10:00:00Z',
    updated_at: '2025-10-14T16:00:00Z',
  },
  {
    id: 2,
    client_id: 1,
    client_name: 'TechVision SAS',
    type: 'ia',
    title: 'Diagnostic Maturité IA — TechVision 2025',
    status: 'termine',
    share_token: 'demo-token-ia-002',
    company_info: {
      company_name: 'TechVision SAS',
      sector: 'Technologie & SaaS',
      employees: '80-100',
      contact_name: 'Isabelle Fontaine',
    },
    answers: {},
    results: {
      global_score: 78,
      sections: [
        { id: 'strategie', title: 'Stratégie & Vision IA', score_pct: 85, preconisations: ['Structurer une roadmap IA sur 3 ans', 'Former le comité de direction aux enjeux IA'] },
        { id: 'donnees', title: 'Qualité & Gouvernance des données', score_pct: 72, preconisations: ['Cataloguer les données disponibles', 'Établir un data quality framework'] },
        { id: 'competences', title: 'Compétences & Organisation', score_pct: 80, preconisations: ['Recruter un AI Product Manager', 'Mettre en place des formations prompt engineering'] },
        { id: 'experimentation', title: 'Expérimentation & Industrialisation', score_pct: 75, preconisations: ['Créer un AI Lab pour les POC', 'Définir des critères de passage en production'] },
      ],
    },
    created_at: '2025-09-22T10:00:00Z',
    updated_at: '2025-10-05T14:00:00Z',
  },
  {
    id: 3,
    client_id: 3,
    client_name: 'MedConnect',
    type: 'cyber',
    title: 'Diagnostic Cybersécurité — MedConnect 2026',
    status: 'en_cours',
    share_token: 'demo-token-cyber-003',
    company_info: {
      company_name: 'MedConnect',
      sector: 'Santé numérique',
      employees: '15-20',
      contact_name: 'Sophie Leroux',
    },
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
]

// ─── PIPELINE CRM ─────────────────────────────────────────────

export const DEMO_PIPELINE: Record<string, Client[]> = {
  decouverte: [DEMO_CLIENTS[5]],
  qualification: [DEMO_CLIENTS[4]],
  negociation: [DEMO_CLIENTS[0]],
  client: [DEMO_CLIENTS[1], DEMO_CLIENTS[2], DEMO_CLIENTS[3]],
  perdu: [DEMO_CLIENTS[6]],
}

// ─── DASHBOARD ───────────────────────────────────────────────

// ca_total  = invoices payee  : 11000+11000+25000+6000 = 53000 HT
// ca_pending = invoices envoyee: 16000+14000 = 30000 HT
// pipeline   = projets en_cours: 85000+48000+12000+35000+28000 = 208000
export const DEMO_DASHBOARD: DashboardData = {
  kpis: {
    total_clients: 7,
    active_clients: 4,
    prospects: 2,
    total_projects: 7,
    active_projects: 5,
    ca_total: 53000,
    ca_pending: 30000,
    pipeline: 208000,
  },
  // Format backend : 8 entrées (phases 0-7), only en_cours projects counted
  phase_distribution: [
    { phase: 0, count: 0 },
    { phase: 1, count: 0 },
    { phase: 2, count: 1 }, // PRJ-2025-005 Stratégie Data
    { phase: 3, count: 1 }, // PRJ-2025-003 RGPD MedConnect
    { phase: 4, count: 1 }, // PRJ-2025-001 Transformation IA
    { phase: 5, count: 1 }, // PRJ-2025-006 Automatisation RH
    { phase: 6, count: 1 }, // PRJ-2025-004 Chatbot IA
    { phase: 7, count: 0 },
  ],
  recent_projects: DEMO_PROJECTS.slice(0, 5),
  recent_clients: DEMO_CLIENTS.slice(0, 5),
}
